let all_products = [
    {
        id:1,
        name:"BLIVE Men Striped..",
        full_name:"Men Striped Round Neck Cotton Blend Multicolor T-Shirt",
        brand_name:"BLIVE",
        description:"The BLIVE Men's Round Neck T-shirt offers a blend of style, comfort, and versatility. Crafted from high-quality cotton fabric, this t-shirt ensures all-day comfort and breathability. Whether you're lounging at home or heading out for casual outings, this t-shirt is an ideal choice. Its simple yet stylish design makes it easy to pair with jeans, shorts, or casual trousers for various occasions.",
        category:"men",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/s/z/l-bmrgyrn-dp-z12-blive-original-imahyvz9dknwfvuf.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/l186t8w0/t-shirt/m/h/n/s-bmrgyrn-z12-blive-original-imagcu32bffhwewr.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/g/5/d/l-bmrgyrn-z12-blive-original-imagx4ehf8xh3cqg.jpeg?q=70&crop=false",
        new_price:299,
        old_price:1999,
        discount:"85% off",
        rating:3.8
    },
    {
        id:2,
        name:"BEWAKOOF Men Full S..",
        full_name:"Oversized Men Graphic Print Round Neck Pure Cotton Brown T-Shirt",
        brand_name:"BEWAKOOF",
        description:"Strike a balance between being young, wild and free with this Beast Within 2.0 Men's Oversized Full Sleeve T-shirt. Pair this brown t-shirt with denim, a varsity jacket and sneakers for a dapper appeal",
        category:"men",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/l/4/n/s-581508-bewakoof-original-imah2e4q8gkhcet5.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/o/r/1/s-581508-bewakoof-original-imah2e4q7wzpcasw.jpeg?q=70",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/k/r/3/s-581508-bewakoof-original-imah2e4qpfhr8y2b.jpeg?q=70&crop=false",
        new_price:494,
        old_price:1499,
        discount:"67% off",
        rating:3.8
    },
    {
        id:3,
        name:"Dennis Lingo Men Fit..",
        full_name:"Men Slim Fit Solid Spread Collar Casual Shirt",
        brand_name:"Dennis Lingo",
        category:"men",
        description:"Enhance your look by wearing this trendy shirt. Team it with a pair of Sharp Looking Chinos and Tassel Loafers for a Dapper Loo",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/b/w/o/s-c301-white-dennis-lingo-original-imafw2ggrk5epcfu-bb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kdj4xow0-0/shirt/n/u/y/xl-c301-white-dennis-lingo-original-imaff64htkhvmzfx.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kdj4xow0-0/shirt/n/j/f/xxl-c301-white-dennis-lingo-original-imaff64hm49trnkk.jpeg?q=70&crop=false",
        new_price:499,
        old_price:1899,
        discount:"80% off",
        rating:4.5
    },
    {
        id:4,
        name:"UNITED DENIM Men Re..",
        full_name:"Men Relaxed Fit Mid Rise Blue Jeans",
        brand_name:"UNITED DENIM",
        category:"men",
        description:"UNITED DENIM Elevate your style with Classic Straight-Leg Jeans. These Jeans offer a modern and flattering silhouette, suitable for various occasions. Crafted for comfort and style, their sleek black hue adds a touch of sophistication to your look. Upgrade your wardrobe with these versatile pants from United Denim.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/f/9/q/32-united192-united-denim-original-imah29yycafyfb4y.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/3/v/c/32-united192-united-denim-original-imah29yysqvftkxp.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/z/j/q/32-united192-united-denim-original-imah29yyhshzpxkg.jpeg?q=70&crop=false",
        new_price:479,
        old_price:2999,
        discount:"84% off",
        rating:3.9
    },
    {
        id:5,
        name:"WROGN Men Solid D..",
        full_name:"Men Solid Denim Jacket",
        brand_name:"WROGN",
        category:"men",
        description:"Olive green solid denim jacket with distressed detail, has a spread collar, 4 pockets, has a button closure, long sleeves, straight hemline.",
        image:"https://rukminim2.flixcart.com/image/612/612/kvtuxe80/jacket/g/j/g/xxl-no-14296102-wrogn-original-imag8nyybzwqe7kv.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kvtuxe80/jacket/x/d/o/xxl-no-14296102-wrogn-original-imag8nyynvvjz6hz.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kvtuxe80/jacket/x/8/2/xxl-no-14296102-wrogn-original-imag8nyyhtah7aez.jpeg?q=70&crop=false",
        new_price:2204,
        old_price:3799,
        discount:"36% off",
        rating:3.7
    },
    {
        id:11,
        name:"Men Regular Fit..",
        full_name:"Men Regular Fit Self Design Spread Collar Casual Shirt",
        brand_name:"CAMPUS SUTRA",
        category:"men",
        description:"Wear this stylish shirt from the house of Campus Sutra. The shirt is comfortable to wear as the fabrics are light on the skin. Using stellar quality solvents, the shirt is made for your daily schedule. Constructed to fit your style spot on and a wide range of sizes to match your persona. Made to not leech out its colours and not lose its shape either. Fetch a casual and cool look for yourself by teaming it with a pair of trousers and sneakers.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/h/k/q/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrswwhtbc4d.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/b/7/t/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrskenp3fdm.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/b/7/t/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrskenp3fdm.jpeg?q=70&crop=false",
        new_price:854,
        old_price:1899,
        discount:"55% off",
        rating:4
    },
    {
        id:12,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Pure Cotton Black T-Shirt",
        brand_name:"Mavinclub",
        category:"men",
        description:"Discover Crazybee's latest collection of oversized t-shirts for men. Shop high-quality, trendy baggy t-shirts that are perfect for everyday wear. Our comfortable oversized t-shirts for men feature modern down-shoulder designs, ensuring you stay stylish and at ease. Whether you're looking for a casual look or something more contemporary, our collection has it all. Find your perfect fit today with Crazybee's premium oversized t-shirts!",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/h/g/h/l-neverlookback-10-mavinclub-original-imah22sjktyjhkrj.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/l/f/r/l-neverlookback-10-mavinclub-original-imah22sjq9pmhazs.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/l/f/r/l-neverlookback-10-mavinclub-original-imah22sjq9pmhazs.jpeg?q=70&crop=false",
        new_price:275,
        old_price:999,
        discount:"72% off",
        rating:3.9
    },
    {
        id:13,
        name:"Men Slim Mid Rise..",
        full_name:"Men Slim Mid Rise Blue Jeans",
        brand_name:"KILLER",
        category:"men",
        description:"Killer Mens Blue Slim Fit Stretchable Knitted Jeans",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/jean/h/o/r/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhkajy6fdh.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/v/k/z/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhxbjqvd4d.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/t/g/x/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhgq8zavzf.jpeg?q=70&crop=false",
        new_price:1539,
        old_price:3899,
        discount:"60% off",
        rating:3.8
    },
    {
        id:104,
        name:"Synthetic Leather Lightw..",
        full_name:"Synthetic Leather Sneakers For Men (White)",
        brand_name:"aadi",
        category:"men",
        description:"Synthetic Leather |Lightweight|Comfort|Summer|Trendy|Walking|Outdoor|Daily Use Sneakers For Men  (White)",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/v/9/6-tm-12-6-trm-white-original-imagjqyzntcvcmhz.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/1/i/p/7-iv-white-7-cooperwings-white-original-imagrpzpvbrhvetq.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/5/7-iv-white-7-cooperwings-white-original-imagrpzpjhryvgyv.jpeg?q=70&crop=false",
        new_price:285,
        old_price:1999,
        discount:"85% off",
        rating:3.6
    },
    {
        id:15,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Festive & Wedding Blazer (Black)",
        brand_name:"FUBAR",
        category:"men",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/x/3/6/l-kcbz-blazer-bk-fubar-original-imahfh5qtt62vaac.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/i/u/3/l-kcbz-blazer-bk-fubar-original-imahfh5qhyfczxyg.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/i/u/3/l-kcbz-blazer-bk-fubar-original-imahfh5qhyfczxyg.jpeg?q=70&crop=false",
        new_price:1499,
        old_price:4999,
        discount:"70% off",
        rating:3.6
    },
    {
        id:69,
        name:"Men Regular Fit Self..",
        full_name:"Mi Notebook 14 Silver -8GB RAM + 256GB SSD, i5 10th Gen + UHD Graphics",
        brand_name:"Xiaomi",
        category:"Mi-Notebook",
        description:"",
        image:"https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1632306189.29356142!600x600!85.jpg",
        image_1:"https://i01.appmifile.com/webfile/globalimg/products/pc/mi-notebook-14/section18.jpg",
        image_2:"https://i01.appmifile.com/webfile/globalimg/products/pc/mi-notebook-14/section14-notebook.png",
        new_price:43999,
        old_price:49999,
        discount:"12%off",
        rating:undefined
    },
    {
        id:99,
        name:"Apple iPhone 15 (Black, 128 GB)",
        full_name:"Apple iPhone 15 (Black, 128 GB)",
        brand_name:"APPLE",
        category:"smartphones",
        description:"Experience the iPhone 15-your dynamic companion. Dynamic Island ensures you stay connected, bubbling up alerts seamlessly while you're busy. Its durable design features infused glass and aerospace-grade aluminum, making it dependable and resistant to water and dust. Capture life with precision using the 48 MP Main Camera, perfect for any shot. Powered by the A16 Bionic Processor, it excels in computational photography and more, all while conserving battery life.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/d/9/-original-imagtc2qzgnnuhxh.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/y/p/n/-original-imagtc5fxzdrdvyc.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/u/m/3/-original-imagtc5ffhbausfy.jpeg?q=70&crop=false",
        new_price:70999,
        old_price:79900,
        discount:"11%off",
        rating:4.6
    },
    {
        id:100,
        name:"Motorola Edge 50 Pro 5G (Black Beauty)",
        full_name:"Motorola Edge 50 Pro 5G with 68W Charger(Black Beauty, 256 GB)(8 GB RAM)",
        brand_name:"MOTOROLA",
        category:"smartphones",
        description:"*8 GB RAM | 256 GB ROM *17.02 cm (6.7 inch) Display *50MP + 13MP + 10MP | 50MP Front Camera *4500 mAh Battery *7 Gen 3 Mobile Platform Processor ,,Motorola Edge 50 Pro has an amalgamation of great designs and amazing features. It embodies a silicone vegan leather finish with a metal frame for a premium feel. Its 17.22 cm (6.7) curved display is Pantone validated for true colours. This 1.5K super HD display, supports HDR10+ and has a refresh rate of 144 Hz to give clear visual effects all the time. Capture beautiful photos with this 50 MP AI-powered camera with OIS that comes with Pantone-validated colours and a f/1.4 wide aperture making it good in low-light conditions.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/e/i/v/-original-imagzhspm6zvfaeh.jpeg?q=70&crop=false",
        image_1:"https://th.bing.com/th/id/OIP.6JeUw485h6bUkeRwjMqKhAAAAA?rs=1&pid=ImgDetMain",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/m/7/i/-original-imagzhspdkgpwb5x.jpeg?q=70&crop=false",
        new_price:31999,
        old_price:36999,
        discount:"13%off",
        rating:4.4
    },
    {
        id:101,
        name:"vivo X Fold3 Pro(Celestial Black)",
        full_name:"vivo X Fold3 Pro(Celestial Black,512 GB)(16 GB RAM)",
        brand_name:"VIVO",
        category:"smartphones",
        description:"16 GB RAM | 512 GB ROM,16.59 cm (6.53 inch) Display,50MP + 50MP + 64MP | 32MP Front Camera,5700 mAh Battery,8Gen 3 Mobile Platform Processor //The X Fold3 Pro is a marvel of modern engineering. With its ultra-slim body at just 1.12 cm thick when folded and weighing a mere 236 g, it offers unparalleled portability without compromising on power. The Carbon Fiber Ultra-durable Hinge ensures longevity, enduring 100 fold-unfold cycles daily for over a decade. ZEISS optics capture life's moments with unrivaled clarity, while the Snapdragon 8 Gen 3 chip delivers blazing performance and energy efficiency. ",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/w/z/j/x-fold3-pro-v2330-vivo-original-imahffy4ztpuhtad.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/v/5/o/x-fold3-pro-v2330-vivo-original-imahffy4qbm5spcx.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/f/k/x/x-fold3-pro-v2330-vivo-original-imahffy4ffsj52xg.jpeg?q=70&crop=false",
        new_price:159999,
        old_price:169999,
        discount:"5%off",
        rating:4.9
    },
    {
        id:102,
        name:"REDMI Note 13 Pro 5G(Scarlet Red,128 GB)(8 GB RAM)",
        full_name:"REDMI Note 13 Pro 5G(Scarlet Red,128 GB)(8 GB RAM)",
        brand_name:"REDMI",
        category:"smartphones",
        description:"8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,200MP (OIS) + 8MP + 2MP | 16MP Front Camera,5100 mAh Battery,7s Gen 2 Mobile Platform 5G Processor //The Redmi Note 13 Pro 5G is not just a smartphone; it's a testament to Xiaomi's commitment to innovation and user satisfaction. With its Pro design, pro camera setup, powerful processor, visual spectacle display, enduring elegance, seamless unlocking, rapid charging, and fan-favourite features, the Redmi Note 13 Pro 5G is the epitome of a next-gen smartphone. Elevate your mobile experience and make a statement with the Redmi Note 13 Pro 5G – where perfection meets Pro.",
        image:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/c/y/-original-imah27s96vp5z7nh.jpeg?q=70&crop=false",
        image_1:"https://mobileinto.com/images/largepic/large_xiaomi-13_2.jpg",
        image_2:"https://th.bing.com/th/id/OIP.b0dLGMZ9JD3GypekPvJSkgAAAA?rs=1&pid=ImgDetMain",
        new_price:24999,
        old_price:28999,
        discount:"13%off",
        rating:4.3
    }
    ,
    {
        id:103,
        name:"realme 12 Pro 5G (Navigator Beige)",
        full_name:"realme 12 Pro 5G(Navigator Beige,128 GB)(8 GB RAM)",
        brand_name:"REALME",
        category:"smartphones",
        description:"8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 8MP + 32MP | 16MP Front Camera,5000 mAh Battery,Snapdragon 6 Gen 1 Processor//In a world dominated by innovation, the realme 12 Pro 5G stands out as a beacon of excellence. It's not just a smartphone; it's a testament to realme's dedication to pushing the boundaries of what's possible. Elevate your mobile experience, capture moments with unprecedented clarity, and indulge in a device that seamlessly blends performance, design, and cutting-edge technology. Choose realme-where every feature is a step toward a future of limitless possibilities.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/m/p/y/12-pro-5g-rmx3842-realme-original-imagxgnhafyjz8rb.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/k/g/w/-original-imagzccb4szfykhg.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/y/h/t/12-pro-5g-rmx3842-realme-original-imagxgnheehh6ebr.jpeg?q=70&crop=false",
        new_price:23999,
        old_price:29999,
        discount:"20%off",
        rating:4.4
    },
    {
        id:104,
        name:"vivo T3 Lite 5G (Vibrant Green)",
        full_name:"vivo T3 Lite 5G (Vibrant Green, 128 GB)(6 GB RAM)",
        brand_name:"VIVO",
        category:"smartphones",
        description:"Experience unparalleled 5G speeds for instant media access and smooth online gaming. Powered by a cutting-edge processor, enjoy seamless gaming, expansive connectivity, and smooth performance. Capture stunning photos with a 50 MP Sony AI main camera and enhance portraits with bokeh effects. With 6 GB RAM + 6 GB Extended RAM, multitask effortlessly. The 90 Hz High Brightness display brings vivid visuals to life. An upgraded battery offers extended playtime, while IP64 Dust and Water Resistance ensures durability.",
        image:"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/h/i/r/t3-lite-5g-v2356-vivo-original-imah27wmfgkergtx.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/z/q/q/-original-imahyz9gvfxa3bbw.jpeg?q=70&crop=false",
        image_2:"https://th.bing.com/th/id/OIP.YtvJn_O9u_pkpbBNh384MwHaHa?rs=1&pid=ImgDetMain",
        new_price:11499,
        old_price:15499,
        discount:"25%off",
        rating:4.4
    },
     {
        id:93,
        name:" Round Rose Gold…",
        full_name:" Round Rose Gold Analog Watch - For Women DRW001",
        brand_name:" Daniel Radcliffe",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/watch/h/z/p/1-drw001-daniel-radcliffe-women-original-imahfv8j7nf4ymv3.jpeg?q=70 ",
        new_price:279,
        old_price:1949,
        discount:"85% off",
        rating:4.1
    },

 {
        id:94,
        name:" Gorgeous Analog Watch… ",
        full_name:" Gorgeous Analog Watch - For Women Diamond Studded Series ",
        brand_name:" Americanviber ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/watch/o/s/g/diamond-studded-series-americanviber-women-original-imah2asyc34pfprk.jpeg?q=70 ",
        new_price:277,
        old_price:699,
        discount:"60% off",
        rating:4
    },

    {
        id:95,
        name:" DRW001 Analog Watch…",
        full_name:" DRW001 Analog Watch - For Women Latest Series",
        brand_name:" Daniel Radcliffe  ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/watch/y/n/2/latest-series-daniel-radcliffe-women-original-imagvtmz7qxyajgh.jpeg?q=70 ",
        new_price:275,
        old_price:1899,
        discount:"85% off",
        rating:4
    },

    {
        id:96,
        name:" Analog Watch – For… ",
        full_name:" Analog Watch - For Women LD-L144-BLU-CH ",
        brand_name:" LOUIS DEVIN  ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/kkmwr680/watch/k/z/j/ld-l144-blu-ch-louis-devin-original-imafzxw9xhhazt53.jpeg?q=70 ",
        new_price:299,
        old_price:1999,
        discount:"85% off",
        rating:4.2
    },

   {
        id:97,
        name:" Gorgeous Analog Watch…",
        full_name:" Gorgeous Analog Watch - For Women Diamond Studded Series ",
        brand_name:" Americanviber  ",
        category:"women-watches",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/watch/u/a/5/diamond-studded-series-americanviber-women-original-imah2asyxezznykz.jpeg?q=70 ",
        new_price:279,
        old_price:699,
        discount:"60% off",
        rating:4
    },

  {
        id:98,
        name:" Sonata - TRNDZ Analog…",
        full_name:"Sonata - TRNDZ Analog Watch - For Women 8123NM01 ",
        brand_name:"SONATA ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/watch/k/s/g/-original-imah7yt3rvspyag9.jpeg?q=70 ",
        new_price:1269,
        old_price:2199,
        discount:"42% off",
        rating:4.5
    },

   {
        id:82,
        name:" Women Layered Blue… ",
        full_name:" Women Layered Blue Dress ",
        brand_name:"AND",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/ktizdzk0/dress/3/x/x/m-fw20an122drl8-and-original-imag6ugtyzcr6u4t.jpeg?q=70 ",
        new_price:2699,
        old_price:2999,
        discount:"10% off",
        rating:4.2
    },

    {
        id:83,
        name:" Women Fit and Flare… ",
        full_name:" Women Fit and Flare Multicolor Dress",
        brand_name:"AND ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/dress/p/e/r/-original-imaghmmfknykmthg.jpeg?q=70 ",
        new_price:2321,
        old_price:2699,
        discount:"14% off",
        rating:4.4
    },

   {
        id:84,
        name:" Women Tiered Blue…",
        full_name:" Women Tiered Blue Dress",
        brand_name:"Janasaya ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/dress/x/o/c/xxl-jac24dr01521-janasya-original-imah8gzx5ddkxjab.jpeg?q=70 ",
        new_price:989,
        old_price:2939,
        discount:"66% off",
        rating:3.5
    },

    {
        id:85,
        name:" Women Bodycon Black… ",
        full_name:" Women Bodycon Black Dress ",
        brand_name:"London Belly ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/dress/f/m/h/s-41-black-london-belly-original-imahyzzzv6kkfgjn.jpeg?q=70 ",
        new_price:299,
        old_price:1299,
        discount:"76% off",
        rating:4.1
    },

    {
        id:86,
        name:" Women Bodycon White… ",
        full_name:" Women Bodycon White Dress ",
        brand_name:" EyeBogler",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/dress/a/q/m/m-dr27-ff-eyebogler-original-imahf3gurbv5gptn.jpeg?q=70",
        new_price:439,
        old_price:2499,
        discount:"82% off",
        rating:4
    },

    {
        id:87,
        name:" Casual Cape Sleeves Printed… ",
        full_name:" Casual Cape Sleeves Printed Women White, Pink, Grey Top ",
        brand_name:"Deera Fashion ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/top/r/u/f/m-deera-deera-fashion-original-imagnc84ajkre9jj.jpeg?q=70",
        new_price:499,
        old_price:999,
        discount:"50% off",
        rating:3.8
    },

    {
        id:88,
        name:" Party Off Shoulder Sleeve… ",
        full_name:" Party Off Shoulder Sleeve Solid Women Black Top ",
        brand_name:"DRAPE AND DAZZLE ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/top/r/b/2/xl-bardot-top-for-womens-drape-and-dazzle-original-imah5za5ngvfz4cw.jpeg?q=70 ",
        new_price:599,
        old_price:1699,
        discount:"64% off",
        rating:3.7
    }
,
    {
        id:89,
        name:" Casual Puff Sleeves… ",
        full_name:" Casual Puff Sleeves Printed Women Yellow Top ",
        brand_name:" SLENOR",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/top/0/f/i/l-sn-t-241-slenor-original-imagzdwgehb73fhh.jpeg?q=70 ",
        new_price:359,
        old_price:1299,
        discount:"72% off",
        rating:3.8
    },

    {
        id:90,
        name:" Casual Regular Sleeves… ",
        full_name:" Casual Regular Sleeves Solid Women Black Top ",
        brand_name:" Redamancii ",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/kshtxu80/top/v/k/l/l-babylock-full-sleeves-redamancii-original-imag6frymhyhk4cz.jpeg?q=70 ",
        new_price:339,
        old_price:998,
        discount:"66% off",
        rating:4
    },

    {
        id:91,
        name:" Casual Bell Sleeves Floral… ",
        full_name:" Casual Bell Sleeves Floral Print Women Light Blue Top ",
        brand_name:" REESE",
        category:"women",
        image:" https://rukminim2.flixcart.com/image/612/612/kw104nk0/shopsy-top/r/s/r/m-body-kansai-mumraa-original-imag8t2gaqvemt27.jpeg?q=70 ",
        new_price:461,
        old_price:1199,
        discount:"61% off",
        rating:3.7
    },

]
export default all_products;
// module.exports = { data: all_products };