let men_data = [
    {
        id:16,
        name:"Dennis Lingo Men Fit..",
        full_name:"Men Slim Fit Solid Spread Collar Casual Shirt",
        brand_name:"Dennis Lingo",
        category:"men",
        description:"Enhance your look by wearing this trendy shirt. Team it with a pair of Sharp Looking Chinos and Tassel Loafers for a Dapper Loo",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/b/w/o/s-c301-white-dennis-lingo-original-imafw2ggrk5epcfu-bb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kdj4xow0-0/shirt/n/u/y/xl-c301-white-dennis-lingo-original-imaff64htkhvmzfx.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kdj4xow0-0/shirt/n/j/f/xxl-c301-white-dennis-lingo-original-imaff64hm49trnkk.jpeg?q=70&crop=false",
        new_price:499,
        old_price:1899,
        discount:"80% off",
        rating:4.5
    },
    {
        id:17,
        name:"Men Regular Fit...",
        full_name:"Men Regular Fit Washed Casual Shirt",
        brand_name:"CAZZBA ",
        category:"men-shirts",
        description:"Available in a myriad of styles, fabrics, and designs, men's shirts cater to a range of preferences and dress codes, from casual to formal settings.This casual wear shirt from has been made with 100% cotton. We have made sure that it matches with your comfort level in all the seasons through out the year. You can wear this shirt to your office, to any get together or to any other casual occasions.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/4/o/5/xxl-cz-den-023-01-cazzba-original-imagnkpygadprdaw.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/v/g/r/xxl-cz-den-023-01-cazzba-original-imagnkpykh7kmcut.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/q/f/f/xxl-cz-den-023-01-cazzba-original-imagnkpyhsuxujzy.jpeg?q=70&crop=false",
        new_price:439,
        old_price:1999,
        discount:"78% off",
        rating:4
    },
    {
        id:18,
        name:"Men Slim Fit Chec..",
        full_name:"Men Slim Fit Checkered Spread Collar Casual Shirt",
        brand_name:"Dennis Lingo",
        category:"men-shirts",
        description:"Enhance your look by wearing this trendy shirt. Team it with a pair of Sharp Looking Chinos and Tassel Loafers for a Dapper Look",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/y/8/g/xl-c751-d-blue-dennis-lingo-original-imafnyksvpjybggz-bb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/f/k/b/3xl-c751-d-blue-dennis-lingo-original-imahfgzssjfaayk6.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/m/l/g/3xl-c751-d-blue-dennis-lingo-original-imahfgzshgsu26af.jpeg?q=70&crop=false",
        new_price:549,
        old_price:2499,
        discount:"78% off",
        rating:4.1
    },
    {
        id:19,
        name:"Men Slim Fit Chec..",
        full_name:"Men Slim Fit Checkered Cut Away Collar Casual Shirt",
        brand_name:"HIGHLANDER",
        category:"men-shirts",
        description:"Highlander Men Slim Full Sleeve Shirt Pink",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/u/f/6/m-phsh000014-highlander-original-imagz7uftn77yhg9.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/z/m/g/m-phsh000014-highlander-original-imagz7ufyfanfwgm.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/w/n/x/m-phsh000014-highlander-original-imagz7uftyy9tfnt.jpeg?q=70&crop=false",
        new_price:511,
        old_price:1799,
        discount:"71% off",
        rating:4.1
    },
    {
        id:20,
        name:"Men Regular Fit..",
        full_name:"Men Regular Fit Self Design Spread Collar Casual Shirt",
        brand_name:"CAMPUS SUTRA",
        category:"men-shirts",
        description:"Wear this stylish shirt from the house of Campus Sutra. The shirt is comfortable to wear as the fabrics are light on the skin. Using stellar quality solvents, the shirt is made for your daily schedule. Constructed to fit your style spot on and a wide range of sizes to match your persona. Made to not leech out its colours and not lose its shape either. Fetch a casual and cool look for yourself by teaming it with a pair of trousers and sneakers.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/h/k/q/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrswwhtbc4d.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/b/7/t/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrskenp3fdm.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/b/7/t/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrskenp3fdm.jpeg?q=70&crop=false",
        new_price:854,
        old_price:1899,
        discount:"55% off",
        rating:4
    },
    {
        id:21,
        name:"Men Slim Fit Check..",
        full_name:"Men Slim Fit Checkered Spread Collar Casual Shirt",
        brand_name:"WROGN",
        category:"men-shirts",
        description:"Give an exemplary look to your casual assortment with this shirt from WROGN.The shirt is comfortable to wear as the fabrics are light on the skin. Using stellar quality solvents, the shirt is made for your daily schedule. Constructed to fit your style spot on and a wide range of sizes to match your persona. Made to not leech out its colours and not lose its shape either.",
        image:"https://rukminim2.flixcart.com/image/832/832/k7gikcw0/shirt/n/a/y/44-11361492-wrogn-original-imafpzexjpyevzfy.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/k7gikcw0/shirt/n/a/y/44-11361492-wrogn-original-imafpzexygcntrvw.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/k7gikcw0/shirt/n/a/y/44-11361492-wrogn-original-imafpzexggxxntkk.jpeg?q=70&crop=false",
        new_price:1296,
        old_price:2399,
        discount:"45% off",
        rating:4
    },
    {
        id:22,
        name:"Men Slim Fit Check..",
        full_name:"Men Slim Fit Checkered Cut Away Collar Casual Shirt",
        brand_name:"KETCH",
        category:"men-shirts",
        description:"Boasting a slim fit, this shirt exudes a polished, tailored appearance, ensuring you look sharp and put-together. And, the cut-away collar is a unique feature that can give you a distinct, stylish edge. Moreover, the three-quarter sleeves can provide coverage and flexibility, making it ideal for any season, while its curved hem and front pocket allow you to exude additional style and convenience.",
        image:"https://rukminim2.flixcart.com/image/612/612/kvlaaa80/shirt/g/t/n/l-khsh000333-ketch-original-imag8gmyy4mgcajh.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kvlaaa80/shirt/y/y/n/l-khsh000333-ketch-original-imag8gmyytdxzeng.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kvlaaa80/shirt/f/x/v/l-khsh000333-ketch-original-imag8gmyh7gcmfjv.jpeg?q=70&crop=false",
        new_price:482,
        old_price:899,
        discount:"46% off",
        rating:3.8
    },
    {
        id:23,
        name:"Men Slim Fit Check..",
        full_name:"Men Slim Fit Checkered Spread Collar Casual Shirt",
        brand_name:"The Indian Garage Co. ",
        category:"men-shirts",
        description:"Men Slim Fit Checkered Spread Collar Casual Shirt",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/s/b/w/-original-imagz8h9b6uhqarq.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/a/r/g/-original-imagz8h9yzatr7ns.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/4/d/o/-original-imagz8h99mbcey58.jpeg?q=70&crop=false",
        new_price:489,
        old_price:1749,
        discount:"72% off",
        rating:4.1
    },
    {
        id:24,
        name:"Men Regular Fit Ch..",
        full_name:"Men Regular Fit Checkered Casual Shirt",
        brand_name:"The Indian Garage Co. ",
        category:"men-shirts",
        description:"Boasting a slim fit, this shirt exudes a polished, tailored appearance, ensuring you look sharp and put-together. And, the cut-away collar is a unique feature that can give you a distinct, stylish edge. Moreover, the three-quarter sleeves can provide coverage and flexibility, making it ideal for any season, while its curved hem and front pocket allow you to exude additional style and convenience.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/t/7/s/-original-imagwghu9pkwjuhy.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/s/7/d/-original-imagwghuuvsduwhf.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/u/t/d/-original-imagwghuwtjwxgkv.jpeg?q=70&crop=false",
        new_price:506,
        old_price:1949,
        discount:"74% off",
        rating:4.5
    },
    {
        id:25,
        name:"Men Printed Round..",
        full_name:"Men Printed Round Neck Polyester White, Black T-Shirt",
        brand_name:"sti",
        category:"men-tshirts",
        description:"Capture your best moments in style with our Black and White Checkered Shirt. This trendy shirt features a classic checkered pattern that adds a touch of sophistication to your look. Made from high-quality materials, it offers both comfort and durability. Whether you're exploring new places or attending social events, this shirt is perfect for any occasion.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/o/t/m-gucci-tshirt-sti-original-imahf7w3dkxzkd6g.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/o/c/g/m-gucci-tshirt-sti-original-imahf7w3mkmzdkxb.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/o/c/g/m-gucci-tshirt-sti-original-imahf7w3mkmzdkxb.jpeg?q=70&crop=false",
        new_price:199,
        old_price:999,
        discount:"80% off",
        rating:3.9
    },
    {
        id:26,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Cotton Blend Blue T-Shirt",
        brand_name:"Leotude",
        category:"men-tshirts",
        description:"Leotude Oversized T-shirt is to make you style in the minds of people. Leotude Oversized t-shirt meticulously crafted with Cotton Blend fabric, bio washed for extra softness. The cozy style will be perfect addition to your fashion apparel. Pair it with tracks, Chinos or Jeans for an urban looks, Grab the Leotude Oversized T shirts now with our pocket friendly prices. Available in different patterns, colors and sizes.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/i/k/b/s-fs49-blue-gorilla-c1-leotude-original-imahfzwzyfp25ec2.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shopsy-t-shirt/4/r/d/3xl-shopsy-rts1-nb-3xl-leotude-urbanice-original-imahft4rn3rgcwug.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shopsy-t-shirt/5/a/r/3xl-shopsy-rts1-nb-3xl-leotude-urbanice-original-imahft4rjpzqtrue.jpeg?q=70&crop=false",
        new_price:329,
        old_price:1099,
        discount:"70% off",
        rating:4
    },
    {
        id:27,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Cotton Blend Pink T-Shirt",
        brand_name:"Jack Paris",
        category:"men-tshirts",
        description:"Discover the epitome of comfort and style with JACK PARIS' Men's oversized t-shirt. Made from a luxurious cotton blend material, this versatile piece offers effortless elegance and all-day comfort. With its oversized fit, it's perfect for lounging or pairing with your favorite jeans for a casual chic look.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/m/v/s-courage-the-cowardly-dog-men-1-pink-s-jack-paris-original-imahfv79cqyhz4bt.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/f/a/q/m-astro-men-3-pink-m-jack-paris-original-imahf6b2gnxed6sm.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/k/x/q/l-astro-men-3-pink-l-jack-paris-original-imahfyn4t7vxgq4m.jpeg?q=70&crop=false",
        new_price:440,
        old_price:1499,
        discount:"70% off",
        rating:undefined
    },
    {
        id:28,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Pure Cotton Black T-Shirt",
        brand_name:"Mavinclub",
        category:"men-tshirts",
        description:"Discover Crazybee's latest collection of oversized t-shirts for men. Shop high-quality, trendy baggy t-shirts that are perfect for everyday wear. Our comfortable oversized t-shirts for men feature modern down-shoulder designs, ensuring you stay stylish and at ease. Whether you're looking for a casual look or something more contemporary, our collection has it all. Find your perfect fit today with Crazybee's premium oversized t-shirts!",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/h/g/h/l-neverlookback-10-mavinclub-original-imah22sjktyjhkrj.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/l/f/r/l-neverlookback-10-mavinclub-original-imah22sjq9pmhazs.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/l/f/r/l-neverlookback-10-mavinclub-original-imah22sjq9pmhazs.jpeg?q=70&crop=false",
        new_price:275,
        old_price:999,
        discount:"72% off",
        rating:3.9
    },
    {
        id:29,
        name:"Men Striped Round N..",
        full_name:"Men Striped Round Neck Cotton Blend Light Green T-Shirt",
        brand_name:"FIONAA TRENDZ ",
        category:"men-tshirts",
        description:"This oversized fit elevates your experience and lets you enjoy all-day comfort. The oversized fit is loose around the shoulders, arms, chest and waist to give you superior comfort and enhance your breathability. It helps create a laidback and easygoing look to give you a stylish appeal.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/m/a/w/l-oversized-fionaa-trendz-original-imagmngnkxscynyz.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/7/j/a/l-oversized-fionaa-trendz-original-imagmngn7yqtbrk6.jpeg?q=70&crop=false",
        Image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/b/f/k/l-oversized-fionaa-trendz-original-imagmngnvy8qtdrz.jpeg?q=70&crop=false",
        new_price:255,
        old_price:999,
        discount:"74% off",
        rating:3.9
    },
    {
        id:30,
        name:"Oversized Men Printed..",
        full_name:"Oversized Men Printed, Round Neck Pure Cotton Navy Blue T-Shirt",
        brand_name:"Veirdo",
        category:"men-tshirts",
        description:"This oversized, relaxed fit longline t-shirt features a brand logo typography print and is perfect for casual wear. The relaxed fit will make you feel at ease, while the longline and drop shoulder sleeves are always a great option for anyone who wants to feel free and relaxed. This amazing t-shirt is from the collection and can be paired with blue ribbed jeans and sneakers for a casual outing.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/p/v/l-os-100-vdorgnl-nvy-veirdo-original-imah256cvtzjwn5r.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/y/x/n/l-os-100-vdorgnl-nvy-veirdo-original-imah256cdczaxbdt.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/t/5/d/l-os-100-vdorgnl-nvy-veirdo-original-imah256ckqzvwrre.jpeg?q=70&crop=false",
        new_price:359,
        old_price:1199,
        discount:"70% off",
        rating:4.1
    },
    {
        id:31,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Pure Cotton White T-Shirt",
        brand_name:"BUKKL",
        category:"men-tshirts",
        description:"Create a cool and lasting impression in this Hip Hop,attitude,Loose fit,Round-Neck,Half sleeves,Printed, Oversized,Back printed T shirt for men from BUKKL. Beautifully Crafted with a cotton fabric and a trendy loose fitting,drop shoulder t shirts fit having attitude print at front and back making it more comfortable to wear during all seasons as gym wear, party wear, casual wear.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-t-shirt/x/b/o/xl-t-29-1st-bukkl-original-imagnwdswu5jv4gj.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/z/w/p/m-t-29-1st-bukkl-original-imah2hn3sxktdxhz.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/z/w/p/m-t-29-1st-bukkl-original-imah2hn3sxktdxhz.jpeg?q=70&crop=false",
        new_price:299,
        old_price:1999,
        discount:"85% off",
        rating:4
    },
    {
        id:32,
        name:"Men Tapered Fit Mid..",
        full_name:"Men Tapered Fit Mid Rise Light Blue Jeans",
        brand_name:"HIGHLANDER",
        category:"men-jeans",
        description:"deal For-Men,Suitable For-Western Wear,Pack Of-1,Pocket Type-Coin Pocket, Curved Pocket,Pattern-Solid,Reversible-No,Sales Package-1 Jean,Closure-Button,Fabric-Cotton Blend,Faded-Clean Look,Rise-Mid Rise,Distressed-Clean Look,Color-Light Blue,Fit-Regular Fit,Fly-Zipper",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/x/u/i/36-hljn001993-highlander-original-imagajtfg8an4f9j-bb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kyag87k0/jean/v/p/k/36-hljn001993-highlander-original-imagajtfbckkpugb.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kyag87k0/jean/u/s/a/36-hljn001993-highlander-original-imagajtfhkzptray.jpeg?q=70&crop=false",
        new_price:723,
        old_price:1799,
        discount:"59% off",
        rating:3.8
    },
    {
        id:33,
        name:"Men Relaxed Fit Mid..",
        full_name:"Men Relaxed Fit Mid Rise Blue Jeans",
        brand_name:"DENIM FIT",
        category:"men-jeans",
        description:"UNITED DENIM Elevate your style with Classic Straight-Leg Jeans. These Jeans offer a modern and flattering silhouette, suitable for various occasions. Crafted for comfort and style, their sleek black hue adds a touch of sophistication to your look. Upgrade your wardrobe with these versatile pants from United Denim.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/f/9/q/32-united192-united-denim-original-imah29yycafyfb4y.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/3/v/c/32-united192-united-denim-original-imah29yysqvftkxp.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/z/j/q/32-united192-united-denim-original-imah29yyhshzpxkg.jpeg?q=70&crop=false",
        new_price:655,
        old_price:2999,
        discount:"78% off",
        rating:3.9
    },
    {
        id:34,
        name:"Men Relaxed Fit Mid..",
        full_name:"Men Relaxed Fit Mid Rise Blue Jeans",
        brand_name:"UNITED DENIM",
        category:"men-jeans",
        description:"UNITED DENIM Elevate your style with Classic Blue Straight-Leg Jeans. These Jeans offer a modern and flattering silhouette, suitable for various occasions. Crafted for comfort and style, their sleek black hue adds a touch of sophistication to your look. Upgrade your wardrobe with these versatile black pants from United Denim.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/z/r/s/28-united71-united-denim-original-imahyhw6wdzehdzq.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/h/m/l/28-united71-united-denim-original-imahyhw6sccpwseh.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/a/z/7/28-united71-united-denim-original-imahyhw6zdgaf8gf.jpeg?q=70&crop=false",
        new_price:659,
        old_price:2999,
        discount:"78% off",
        rating:3.9
    },
    {
        id:35,
        name:"Men Slim Mid Rise..",
        full_name:"Men Slim Mid Rise Blue Jeans",
        brand_name:"KILLER",
        category:"men-jeans",
        description:"Killer Mens Blue Slim Fit Stretchable Knitted Jeans",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/jean/h/o/r/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhkajy6fdh.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/v/k/z/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhxbjqvd4d.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/t/g/x/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhgq8zavzf.jpeg?q=70&crop=false",
        new_price:1539,
        old_price:3899,
        discount:"60% off",
        rating:3.8
    },
    {
        id:36,
        name:"Men Jogger Fit Mid..",
        full_name:"Men Jogger Fit Mid Rise Black Jeans",
        brand_name:"Nayak Fashion",
        category:"men-jeans",
        description:"NAYAK FASHION presents this streachable Denim fabric Cargo. It's good quality fabric would certainly make you feel good and confident when you wear it. Comfortable 6 Pocket pockets with7 inches and one coin. pocketwith 2.5, comfortable 2 back pockets with 7 inches,Length of this jeans is 41 inch. highly durable and stretchable jeans pant for man.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/n/i/6/30-01-jean-loose-black-nayak-fashion-original-imagvagjf9quxsbt.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/z/s/c/30-o-black-tissu-amour-original-imagrvgzuwcx8sc6.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/m/o/w/30-o-black-tissu-amour-original-imagrvgzgfzy3sjr.jpeg?q=70&crop=false",
        new_price:497,
        old_price:1999,
        discount:"75% off",
        rating:3.8
    },
    {
        id:37,
        name:"Men Slim Low Rise..",
        full_name:"Men Slim Low Rise Dark Blue Jeans",
        brand_name:"Louis Philippe Jeans ",
        category:"men-jeans",
        description:"Men Slim Low Rise Dark Blue Jeans",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/b/g/j/32-lrdncslpo78544-louis-philippe-jeans-original-imagu2mszzbqqysh.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/q/x/v/32-lrdncslpo78544-louis-philippe-jeans-original-imagu2msspgchw2z.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/p/x/1/32-lrdncslpo78544-louis-philippe-jeans-original-imagu2msyygzkhnb.jpeg?q=70&crop=false",
        new_price:1767,
        old_price:2599,
        discount:"32% off",
        rating:4
    },
    {
        id:38,
        name:"Men Relaxed Fit M..",
        full_name:"Men Relaxed Fit Mid Rise Light Blue Jeans",
        brand_name:"UNITED DENIM",
        category:"men-jeans",
        description:"UNITED DENIM Elevate your style with Classic Straight-Leg Jeans. These Jeans offer a modern and flattering silhouette, suitable for various occasions. Crafted for comfort and style, their sleek black hue adds a touch of sophistication to your look. Upgrade your wardrobe with these versatile pants from United Denim.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/t/v/j/28-united069-united-denim-original-imahyur5964ehvjn.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/f/j/y/28-united069-united-denim-original-imahyur5udhgggvu.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/r/h/y/28-united069-united-denim-original-imahyur58ghpfsut.jpeg?q=70&crop=false",
        new_price:649,
        old_price:2999,
        discount:"78% off",
        rating:3.9
    },
    {
        id:117,
        name:"Synthetic Leather Lightw..",
        full_name:"Synthetic Leather Daily Use Sneakers For Men (White)",
        brand_name:"aadi",
        category:"men-shoes",
        description:"Synthetic Leather |Lightweight|Comfort|Summer|Trendy|Walking|Outdoor|Daily Use Sneakers For Men  (White)",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/v/9/6-tm-12-6-trm-white-original-imagjqyzntcvcmhz.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/1/i/p/7-iv-white-7-cooperwings-white-original-imagrpzpvbrhvetq.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/5/7-iv-white-7-cooperwings-white-original-imagrpzpjhryvgyv.jpeg?q=70&crop=false",
        new_price:285,
        old_price:1999,
        discount:"85% off",
        rating:3.6
    },
    {
        id:118,
        name:"Casual Sneaker Shoes..",
        full_name:" Classic Rounded Toe, Soothing Insole Sneakers For Men (Blue, Off White)",
        brand_name:"Red Tape",
        category:"men-shoes",
        description:"Engage with the Red Tape's Casual Sneaker Shoes for Men, an awesome piece to drool upon! A chic low-cut pattern in an off-white/blue color with a durable Memory foam + TPR sole gives it the ability to temporarily retain its shape after being compressed.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/n/o/f/-original-imahfxv9rwh5nvhp.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/u/o/y/11-rsl056-11-red-tape-off-white-blue-original-imah28zvqpqkpvns.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/u/o/y/11-rsl056-11-red-tape-off-white-blue-original-imah28zvqpqkpvns.jpeg?q=70&crop=false",
        new_price:1649,
        old_price:5499,
        discount:"70% off",
        rating:4.3
    },
    {
        id:119,
        name:"Boots For Men(Bla..",
        full_name:"Boots For Men  (Black)",
        brand_name:"Vellinto",
        category:"men-shoes",
        description:"Vellinto carries classic Slip-On design with an anti rusting side zip, for a look that never goes out of style. This Shoe brings you comfort all day around. It is nice affordable shoes for everyday use, or wedding or formal occasion. Vellinto makes a statement of its own with a variety in men's casual footwear with unique style and new trends for every occasion",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/e/j/e/6-art-ca474-vellinto-black-original-imahy5mxqzxrhezg.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/5/b/0/6-art-ca474-vellinto-black-original-imahy5mxyyr3vmtc.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/5/n/n/6-art-ca474-vellinto-black-original-imahy5mxmv2fzyfx.jpeg?q=70&crop=false",
        new_price:696,
        old_price:1999,
        discount:"65% off",
        rating:4.4
    },
    {
        id:120,
        name:"Puma Smashic Sneak..",
        full_name:"Puma Smashic Sneakers For Men  (White)",
        brand_name:"PUMA",
        category:"men-shoes",
        description:"Ring in the new season with Style with a pair of PUMA shoes perfect to make this summer, better !",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/q/g/l/-original-imagsfdvebvyzkxa.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/y/s/3/11-394371-puma-white-matte-silver-original-imaghkpfbwtvwrqc.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/y/s/3/11-394371-puma-white-matte-silver-original-imaghkpfbwtvwrqc.jpeg?q=70&crop=false",
        new_price:1999,
        old_price:4499,
        discount:"55% off",
        rating:4.1
    },
    {
        id:121,
        name:"Loafers For Men (Bro..",
        full_name:"Loafers For Men  (Brown)",
        brand_name:"Bata",
        category:"men-shoes",
        description:"Color-Brown,Outer material-Synthetic,Ideal for-Men,Occasion-Casual,Type For Casual-Loafers,Closure-Slip-On",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/m/y/a/-original-imaghhz3mzfrghf3.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/e/u/7-8513008-7-bata-brown-original-imagjzw4rhpx6rkp.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/f/l/k/7-8513008-7-bata-brown-original-imagjzw45duycbrg.jpeg?q=70&crop=false",
        new_price:692,
        old_price:999,
        discount:"30% off",
        rating:4.1
    },
    {
        id:44,
        name:"Men Solid Cotton Ble..",
        full_name:"Men Solid Cotton Blend Straight Kurta  (White)",
        brand_name:"SOPANI",
        category:"men-ethnics",
        description:"Refresh your wardrobe with this Straight Kurta from SOPANI. This Regular Straight Kurta is a perfect partner for all your ethnic wear and casual needs.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/j/z/u/m-chainlster-sopani-original-imagtjhdf7azz8n2.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/k/y/v/m-chainlster-sopani-original-imagtjhdt2sguffz.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/w/c/b/xl-chainlster-sopani-original-imagq2x3teec5dez.jpeg?q=70&crop=false",
        new_price:369,
        old_price:1499,
        discount:"75% off",
        rating:4
    },
    {
        id:45,
        name:"Men Printed Cotton B..",
        full_name:"Men Printed Cotton Blend Straight Kurta  (Yellow)",
        brand_name:"FRELURO ",
        category:"men-ethnics",
        description:"This Trendy And Attractive Men's Pathani kurta And Look Stylish Effortlessly. Made To Accentuate Any Body Type, It Will Give You That Extra Oomph And Make You Stand Out Wherever You Are. This kurta Is Ideal For The Party,Ocassional,Festive,Evening, Valentines Day, Birthday, casual, Etc.The Kurta Is Made Of Standard Fabric Material Which Feels Very Smooth On Skin.. It features Full sleeve, Shirt Collar.Festival/Casual wear Men's Cotton fabric kurta with long sleeves and Cut away collar that you pair with pajama,churidar,jeans.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/s/7/b/xl-grey-102-yellow-freluro-original-imagc26vhphceetj-bb.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/l08gsy80/kurta/x/l/g/xl-grey-102-yellow-freluro-original-imagc26vehgey2gp.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/l08gsy80/kurta/u/2/5/xl-grey-102-yellow-freluro-original-imagc26vyv9zhdwk.jpeg?q=70&crop=false",
        new_price:336,
        old_price:999,
        discount:"66% off",
        rating:3.9
    },
    {
        id:46,
        name:"Men Embroidered Co..",
        full_name:"Men Embroidered Cotton Silk Straight Kurta  (Black)",
        brand_name:"Nellist",
        category:"men-ethnics",
        description:"Men Embroidered Cotton Silk Straight Kurta  (Black)",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/4/c/p/m-only-kurta-box-nellist-original-imagvmkmtedryv9t.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/p/s/s/m-box-kurta-nellist-original-imahygkcczrq9czh.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/3/s/z/m-box-kurta-nellist-original-imahygkcwmya2bec.jpeg?q=70&crop=false",
        new_price:499,
        old_price:1999,
        discount:"75% off",
        rating:3.7
    },
    {
        id:47,
        name:"Men Solid Cotton Bl..",
        full_name:"Men Solid Cotton Blend Straight Kurta  (White)",
        brand_name:"DEELMO",
        category:"men-ethnics",
        description:"Kurta that's made from 80% cotton and 20% polyester, linen, or rayon. Cotton blend means your Kurta will have the same feel as a cotton tee, but it's a little more lightweight and resistant to wrinkles. Soft comfortable and skin-friendly, super cozy and warm. It does not irritate the skin while worn. Whether hanging out or heading into work, you will feel comfortable with this Solid Kurta",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/q/v/4/xl-uplkih04-dimmy-original-imagwnbnjgj8rwut.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/m/q/s/xxl-derfv04-deelmo-original-imagwzzzujt2r3wj.jpeg?q=70",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/l/d/u/xl-uplkih04-dimmy-original-imagwnbnnkyqzqwc.jpeg?q=70&crop=false",
        new_price:494,
        old_price:1999,
        discount:"75% off",
        rating:4
    },
    {
        id:48,
        name:"Men Embroidered Cotton..",
        full_name:"Men Embroidered Cotton Silk Straight Kurta  (Dark Blue)",
        brand_name:"vinaari fab",
        category:"men-ethnics",
        description:"Elevate your ethnic wardrobe with our stunning Embroidered Men's Kurta Set, designed to make a statement on any occasion. Meticulously handcrafted by skilled artisans, the kurta features intricate embroidery that exudes elegance and charm. Made from high-quality fabric, it ensures both comfort and durability. The classic design is complemented by the churidar pants, providing a perfect fit and a touch of contemporary flair.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/q/8/n/s-big-kaju-katli-kaashi-couture-original-imagsbyrkzgdtbg7.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/b/o/c/s-big-kaju-katli-kaashi-couture-original-imagsbyrnvbegeh3.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/6/c/e/s-big-kaju-katli-kaashi-couture-original-imagsbyrfjw5tr2b.jpeg?q=70&crop=false",
        new_price:399,
        old_price:1999,
        discount:"80% off",
        rating:3.7
    },
    {
        id:49,
        name:"Men Cotton Blend K..",
        full_name:"Men Cotton Blend Kurta Pyjama Set",
        brand_name:"FABWAX",
        category:"men-ethnics",
        description:"FABWAX brings to you Men's Tunic Ethnic Wear Kurta Pajama Set that is designed for special occasions where you wish to look your best. This 2-piece set includes a long button-down kurta and drawstring pajama. Traditional design on this kurta captures all of the details of the classic Indian men's garment with long sleeves, a long hemline with side vents, and a mandarin collar.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/t/z/h/xl-an-lp-k-only-anrex-original-imagyhkur4ynpg3p.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/g/c/j/m-lp-prntd-st-fabwax-original-imagymygenpmgghz.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/x/r/9/xl-an-lp-k-only-anrex-original-imagyhkur5pkhrs6.jpeg?q=70&crop=false",
        new_price:497,
        old_price:1699,
        discount:"70% off",
        rating:3.9
    },
    {
        id:50,
        name:"N.B.F Fashion Print..",
        full_name:"N.B.F Fashion Printed Sherwani",
        brand_name:"N.B.F FASHION",
        category:"men-ethnics",
        description:"N.B.F Faashion brand brings you quality and affordability. We take pride in our commitment to maintain quality standards in each piece manufactured by us. A true epitome of class, this designer Sherwani Combo will surely reflect your impeccable taste in Fashion. Made from Heavy Jacquard Fabric this set will surely make you the cynosure of all eyes.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/sherwani/c/o/m/l-rj-985-n-b-f-fashion-original-imagweh47h9hdmkz.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/sherwani/q/e/x/l-rj-985-n-b-f-fashion-original-imagweh4n24wpxxg.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/sherwani/g/4/4/l-rj-985-n-b-f-fashion-original-imagweh4d8ehxdgm.jpeg?q=70&crop=false",
        new_price:1694,
        old_price:3999,
        discount:"57% off",
        rating:3.7
    },
    {
        id:51,
        name:"Men Pyjama",
        full_name:"Men Pyjama",
        brand_name:"V-MART",
        category:"men-ethnics",
        description:"V-MART brings you this comfortable pyjama for your wardrobe. This handcrafted pajama is made of the finest and 100% pure cotton. This product comes only in White and the finest cotton available in the market. It can be used with your shirt, kurta, and t-shirt.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/pyjama/y/w/s/36-1509552-v-mart-original-imahyp74mgeexnyg.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/pyjama/e/p/w/36-1509552-v-mart-original-imahyp74huchymtg.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/pyjama/z/q/o/36-1509552-v-mart-original-imahyp74hsbt2bmy.jpeg?q=70&crop=false",
        new_price:199,
        old_price:899,
        discount:"44% off",
        rating:4.1
    },
    {
        id:52,
        name:"EID Festive Wear..",
        full_name:"EID Festive Wear For Men Pyjama",
        brand_name:"VASTRAMAY",
        category:"men-ethnics",
        description:"Vastramay brings to you this Stylish yet Comfortable Men Aqua Pure Cotton Slub Kurta in Exceptionally Attractive Colours. Adorn it for a perfect Classy & Trendy look. Pair it with a juti or a mojari for the Royal fee",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/pyjama/k/y/4/free-vasmpty1wh-vastramay-original-imagfanh5cgzhe6y-bb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kmds4nk0/pyjama/x/e/d/free-vasmpty1wh-vastramay-original-imagfanhea4hcsuz.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kmds4nk0/pyjama/b/c/9/free-vasmpty1wh-vastramay-original-imagfanhmnhaqma7.jpeg?q=70&crop=false",
        new_price:395,
        old_price:1999,
        discount:"80% off",
        rating:3.7
    },
    {
        id:53,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Festive & Wedding Blazer (Black)",
        brand_name:"FUBAR",
        category:"men-blazers",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/x/3/6/l-kcbz-blazer-bk-fubar-original-imahfh5qtt62vaac.jpeg?q=70",
        new_price:1499,
        old_price:4999,
        discount:"70% off",
        rating:3.6
    },
    {
        id:54,
        name:"Men Solid Single Bre..",
        full_name:"Men Solid Single Breasted Casual, Formal, Festive & Wedding, Party Blazer  (Black)",
        brand_name:"Darbar In",
        category:"men-blazers",
        description:"Shop from a wide range of Blazer from DARBAR IN. Perfect for office meetings and parties, you could pair it with a stylish shirt to complete the look.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/n/x/c/42-black-collection-darbar-in-original-imahfymxqybgf6zs.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/c/w/5/42-black-collection-darbar-in-original-imahfymxh887fqgg.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/c/w/5/42-black-collection-darbar-in-original-imahfymxh887fqgg.jpeg?q=70&crop=false",
        new_price:1529,
        old_price:5999,
        discount:"74% off",
        rating:3.5
    },
    {
        id:55,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Casual, Formal Blazer(Green)",
        description:"Shop from a wide range of Blazer from HUMJOLI MENS WEAR . Perfect for office meetings and parties, you could pair it with a stylish shirt to complete the look.",
        brand_name:"HUMJOLI MENS WEAR ",
        category:"men-blazers",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/u/z/y/xxl-xe-n4-grn-humjoli-mens-wear-original-imagywmu2pczhfr3.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/l/p/p/xxl-xe-n4-grn-humjoli-mens-wear-original-imagywmuukzeaqe6.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/l/p/p/xxl-xe-n4-grn-humjoli-mens-wear-original-imagywmuukzeaqe6.jpeg?q=70&crop=false",
        new_price:1509,
        old_price:7999,
        discount:"81% off",
        rating:3.5
    },
    {
        id:56,
        name:"Men Checkered Single..",
        full_name:"Men Checkered Single Breasted Formal Blazer  (Brown)",
        brand_name:"PARK AVENUE ",
        category:"men-blazers",
        description:"Men Checkered Single Breasted Formal Blazer  (Brown)",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/g/k/w/-original-imahyy6hbkhkh8f3.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/e/e/s/-original-imahyy6hehacsxcn.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/n/g/j/-original-imahyy6hqdmbfnwf.jpeg?q=70&crop=false",
        new_price:3519,
        old_price:7999,
        discount:"56% off",
        rating:undefined
    },
    {
        id:108,
        name:"Apple AirPods(2nd gen)",
        full_name:"Apple AirPods(2nd gen) with Charging Case Bluetooth Headset ",
        brand_name:"APPLE",
        description:"Apple AirPods(2nd gen) with Charging Case Bluetooth Headset with Mic  (White, True Wireless) The new AirPods combine intelligent design with breakthrough technology and crystal clear sound. Powered by the new Apple H1 headphone chip, AirPods now feature hands-free access to Siri using just your voice. And up to 3 hours of talk time on a single charge.",
        category:"men-earbuds",
        image:"https://rukminim2.flixcart.com/image/612/612/kpinwy80/headphone/x/r/e/mmef2hn-a-apple-original-imag3qe9hphsevrt.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kpinwy80/headphone/m/5/1/mmef2hn-a-apple-original-imag3qe993fzdbcz.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kpinwy80/headphone/z/4/x/mmef2hn-a-apple-original-imag3qe93vvmf4mu.jpeg?q=70&crop=false",
        new_price:8499,
        old_price:12900,
        discount:"34%off",
        rating:4.5
    },
    {
        id:109,
        name:"realme Buds T110 ",
        full_name:"realme Buds T110 with AI ENC for calls",
        description:"realme Buds T110 with AI ENC for calls, upto 38 hours of Playback and Fast Charging Bluetooth Headset  (Jazz Blue, True Wireless) : the realme Buds T110, designed to provide an immersive music and gaming experience,with 10 MM Dynamic Boost Drivers to deliver powerful and dynamic sound to enhance your listening experience & low latency of 88ms for smooth and lag-free audio while gaming or watching videos.",
        brand_name:"REALME",
        category:"men-earbuds",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/a/5/0/-original-imahy3uqdmgx6qey.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/d/d/t/-original-imahyhdhnqbrqrdr.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/e/m/z/-original-imahyhdhz2vgkyza.jpeg?q=70&crop=false",
        new_price:1399,
        old_price:2999,
        discount:"53%off",
        rating:4.2
    },
    {
        id:110,
        name:"boAt Airdopes 161",
        full_name:"boAt Airdopes 161/163 Bluet.. Headset(Pebble Black,Active Black,True Wireless)",
        brand_name:"boAt",
        category:"men-earbuds",
        description:"boAt Airdopes 161/163 with ASAP Charge & 40 HRS Playback Bluetooth Headset  (Pebble Black, Active Black, True Wireless): It's time to Do Your Groove, with Airdopes161TWS earbuds. The 13mm drivers in the earbuds are there to deliver an immersive listening time. It comes equipped with Bluetooth v5.1 wireless technology so that you can enjoy all of your sessions lag-free.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/o/d/r/-original-imagpgwsm6zgtsrj.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/9/x/u/-original-imagqtpfkwfzdydx.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/o/m/6/-original-imagqtpfj5yvdxwg.jpeg?q=70&crop=false",
        new_price:999,
        old_price:2490,
        discount:"59%off",
        rating:4
    },
    {
        id:111,
        name:"OPPO Enco Buds 2",
        full_name:"OPPO Enco Buds 2 Bluetooth Headset (Midnight, True Wireless)",
        brand_name:"OPPO",
        category:"men-earbuds",
        description:"OPPO Enco Buds 2 with 28 hours Battery life & Deep Noise Cancellation Bluetooth Headset  (Midnight, True Wireless)",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/p/r/z/enco-buds-2-oppo-original-imagh9frfp7gxdb3.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/b/z/w/enco-buds-2-oppo-original-imagh9frdqzy74md.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/v/c/l/enco-buds-2-oppo-original-imagh9frv3ragu9k.jpeg?q=70&crop=false",
        new_price:1799,
        old_price:3999,
        discount:"55%off",
        rating:4.3
    },
    {
        id:66,
        name:"Men Slim Fit Pri...",
        full_name:"Men Slim Fit Printed Formal Shirt",
        brand_name:"PETER ENGLAND",
        category:"men-formals",
        description:"Style Code-PESFWSLBF52607,Fit Slim,Fabric-Pure Cotton,Sleeve-Full Sleeve,Pettern-Printed,Reversible-No",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/w/i/z/40-pesfwslbf52607-peter-england-original-imagtnr8kz5k5ryu.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/q/n/e/40-pesfwslbf52607-peter-england-original-imagtnr8hpdqey7n.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/j/c/v/40-pesfwslbf52607-peter-england-original-imagtnr8ktmhkxfb.jpeg?q=70&crop=false",
        new_price:895,
        old_price:1999,
        discount:"44%off",
        rating:4.1
    },
    {
        id:67,
        name:"Men Regular Fit Sol..",
        full_name:"Men Regular Fit Solid Spread Collar Formal Shirt",
        brand_name:"VTEXX",
        category:"men-formals",
        description:"VTEXX is known for Stylish attire of Formal Shirts and Kurtas. High Quality fabric cotton, Slim-fit, Full Sleeves, Directly From manufacturer at reasonable Prices. Button Design may be change. Color may slightly vary due to Graphics Lighting or your system glow.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/d/w/b/s-13-lstr-peach-vtexx-original-imagxtnyc2c4fgdu.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/k/q/p/s-13-lstr-peach-vtexx-original-imagxtnyzzr22mcc.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/k/i/d/s-13-lstr-peach-vtexx-original-imagxtnygfu4bfn9.jpeg?q=70&crop=false",
        new_price:299,
        old_price:1999,
        discount:"85%off",
        rating:4
    },
    {
        id:68,
        name:"Men Regular Fit Self..",
        full_name:"Men Slim Fit Self Design Spread Collar Formal Shirt",
        brand_name:"RAYMOND",
        category:"men-formals",
        description:"Style Code-RMSX12155-R3,Closure-Button,Fit-Slim,Fabric-Pure Cotton,Sleeve-Full Sleeve,Pattern-Self Design,Reversible-No,Collar-Spread,Color-Red",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/v/4/0/-original-imagqfvhqu2gmtjg.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/z/c/m/-original-imagqfvh6kjtghk4.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/x/p/o/-original-imagqfvhfpchuzz7.jpeg?q=70&crop=false",
        new_price:1049,
        old_price:2199,
        discount:"52%off",
        rating:4.3
    },
    {
        id:112,
        name:"Trending Premium Qu...",
        full_name:"Day & Date Functioning for Boys Analog Watch ",
        description:"Trending Premium Quality Day & Date Functioning for Boys Analog Watch - For Men SK-PG-4078-WYT-BRWN Basic with Day and Date Display:Men will never miss out on his time machine when it comes to his fashion quotient . Apart from being an indispensable tool for making life easier , men's watches are an extension for their personality.",
        brand_name:"PROVOGUE ",
        category:"men-watches",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/e/v/e/1-sk-pg-4078-wyt-brwn-basic-with-day-and-date-display-provogue-original-imahffrywrx3x8zb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/k/5/e/1-sk-pg-4078-wyt-brwn-basic-with-day-and-date-display-provogue-original-imahffry6hyzxtez.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/w/y/c/1-sk-pg-4078-wyt-brwn-basic-with-day-and-date-display-provogue-original-imahffryrhz5gxvw.jpeg?q=70&crop=false",
        new_price:299,
        old_price:2499,
        discount:"88% off",
        rating:3.9
    },
    {
        id:113,
        name:"Analog Watch-For..",
        full_name:"Analog Watch - For Men PE000017B",
        brand_name:"PETER ENGLAND",
        category:"men-watches",
        description:"Analog Watch for Men with Day and Date Display This Watch is an Analog watch with Day and Date Display. Whether you are an office goer, a college-going teenager, or an established man, you cannot deny the satisfaction you get after wearing this watch. The Movement of the watch is Quartz which results in a Cost-Effective Watch. It has Three Hands on the Dial that includes Hours, Minutes, and Seconds.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/v/f/2/-original-imagrdzghye4wtqq.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kg8avm80-0/watch/f/f/3/pe000017b-peter-england-original-imafwgbuhhky2pn4.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kg8avm80-0/watch/0/o/n/pe000017b-peter-england-original-imafwgbuqymdrqs2.jpeg?q=70&crop=false",
        new_price:1467,
        old_price:3045,
        discount:"51% off",
        rating:4.3
    },
    {
        id:114,
        name:"Provogue Functioning S..",
        full_name:"Provogue Functioning Stainless Chain Analog Watch ",
        brand_name:"PROVOGUE",
        description:"Provogue Functioning Stainless Chain Analog Watch - For Men SK-PG-4076-BLUWYT-SLVR Basic Analog Watch for Men with Day and Date Display This Watch is an Analog watch with Day and Date Display. Whether you are an office goer, a college-going teenager, or an established man, you cannot deny the satisfaction you get after wearing this watch. The Movement of the watch is Quartz which results in a Cost-Effective Watch. It has Three Hands on the Dial that includes Hours, Minutes, and Seconds.",
        category:"men-watches",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/p/a/y/-original-imagrtbrqzwf8fjn.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/8/n/x/1-sk-pg-4076-bluwyt-slvr-basic-analog-watch-for-men-with-day-and-original-imagnec86ddrnrqk.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/q/h/1-sk-pg-4076-bluwyt-slvr-basic-analog-watch-for-men-with-day-and-original-imagnec8fxgayqxz.jpeg?q=70&crop=false",
        new_price:359,
        old_price:2499,
        discount:"85% off",
        rating:3.6
    },
    {
        id:115,
        name:"Tees Analog Watch..",
        full_name:"Tees Analog Watch - For Men 68011PP08",
        brand_name:"Fastrack",
        category:"men-watches",
        description:"Product Details:Water Resistant-Yes,Display Type-Analog,Style Code-68011PP08,Series-Tees,Occasion-Casual,Watch Type-Wrist Watch,Pack of-1,Model Name -68011PP08",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/a/k/e/-original-imagnydrewxe5qeg.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/k8ro3gw0/watch/n/h/w/68011pp08-fastrack-original-imafqpgyxj24wf6b.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/k8ro3gw0/watch/n/h/w/68011pp08-fastrack-original-imafqpgydmyr4mff.jpeg?q=70&crop=false",
        new_price:939,
        old_price:945,
        discount:undefined,
        rating:4.3
    },
    {
        id:116,
        name:"Flynn Analog Watch..",
        full_name:"Flynn Analog Watch-For Men BQ1125",
        brand_name:"FOSSIL",
        category:"men-watches",
        description:"Wear the ultimate expression of Fossil style and design evolution on your wrist with this chronograph watch. Expertly crafted from stainless steel and silver link bracelet, the Flynn series watch ensures form and function for years to come. The classic black dial features a chronograph display for precise timekeeping and a date interface for easy reference.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/0/k/a/-original-imagphkyrrrnaryb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/k1qr5ow0/watch/k/z/z/bq1125-fossil-original-imafh86zh8c8unss.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/k1pbpu80/watch/k/z/z/bq1125-fossil-original-imafh86zeg6gymxw.jpeg?q=70&crop=false",
        new_price:5879,
        old_price:11995,
        discount:"50%off",
        rating:4.3
    },
    {
        id:76,
        name:"boAt Rockerz 460",
        full_name:"boAt Rockerz 460 with upto 30 Hours Playb. Bluetooth Headset(Crimson White)",
        brand_name:"boAt",
        category:"boat-headphones",
        description:"With Mic:Yes,Bluetooth version: 5.2,Wireless range: 10 m,Playback Time: Upto 30 Hours ENx Technology: For Clear Voice Calls Beast Mode: Low latency for Gaming 40mm Drivers: boAt Signature Sound,Crimson White,1 Headphone, Charging Cable, User Manual, Warranty Card",
        image:"https://rukminim2.flixcart.com/image/832/832/l3dcl8w0/headphone/w/7/f/-original-imagehzz29n3whg8.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/l3dcl8w0/headphone/r/n/y/-original-imagehzzhhy43mqv.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/l3dcl8w0/headphone/c/t/9/-original-imagehzzzsfyd8gh.jpeg?q=70&crop=false",
        new_price:1799,
        old_price:2490,
        discount:"27%off",
        rating:4.2
    },
    {
        id:77,
        name:"boAt Rockerz 450",
        full_name:"boAt Rockerz 450 with Upto 15 Hours Playback Bluet. Headset(Luscious Black)",
        brand_name:"boAt",
        category:"boat-headphones",
        description:"With Mic:Yes,Connector type: 3.5 mm,Battery life: 15 hr | Charging time: 3 Hours,40mm Drivers: HD Sound,Adjustable Earcups,Up to 15 H Playback,Bluetooth version 5.0,Dual Modes: Bluetooth & AUXAre you looking for a headset that features eye-catching aesthetics and dual modes? If yes, bring home the boAt Rockerz 450 that has an AUX-mode as well as the Bluetooth connectivity feature. The 40-mm drivers and adjustable earcups ensure you enjoy a comfortable listening experience that is immersive.",
        image:"https://rukminim2.flixcart.com/image/832/832/ksw4ccw0/headphone/w/g/r/rockerz-450-boat-original-imag6cqqh49wjfy5.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/ksw4ccw0/headphone/r/h/w/rockerz-450-boat-original-imag6cqqwzjeufqg.jpeg?q=70&crop=falsee",
        image_2:"https://rukminim2.flixcart.com/image/832/832/ksw4ccw0/headphone/a/d/r/rockerz-450-boat-original-imag6cqqbtyhy2ny.jpeg?q=70&crop=false",
        new_price:1499,
        old_price:3990,
        discount:"62%off",
        rating:4.3
    },
    {
        id:78,
        name:"boAt Rockerz 333 Pro",
        full_name:"boAt Rockerz 333 Pro with 60 Hours Battery Bluetooth Headset(Teal Green)",
        brand_name:"boAt",
        category:"boat-headphones",
        description:"Tune into a peerless way of delving in pure auditory bliss with Rockerz 333 Pro wireless neckband. It offers a humongous playback time of up to 60HRS! Being equipped with ENx tech, this neckband delivers a matchless calling experience by letting you be clearly heard over voice calls. Courtesy our ASAP Charge tech, the neckband can garner up to 20HRS of playtime in just 10Min of charge! It dons magnetic earbuds that support easy storage and carry when not in use.",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/o/9/j/-original-imagg242aegju2ja.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/e/k/w/-original-imagg242zspkzy4q.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/v/c/i/-original-imagg242wadngh9t.jpeg?q=70&crop=false",
        new_price:1099,
        old_price:2990,
        discount:"63%off",
        rating:4.2
    }
    ,
    {
        id:79,
        name:"boAt Rockerz 600",
        full_name:"boAt Rockerz 600 HD Sound Bluetooth Headset(Brown, On the Ear)",
        brand_name:"boAt",
        category:"boat-headphones",
        description:"the boAt Airdopes 131 that comes with a carrying case. This carrying case also acts as a 650 mAh portable charger that extends the playback time of these earbuds by up to 15 hours, i.e. 4 times its normal charging capacity. The normal battery capacity of each of these earbuds is 40 mAh and this delivers up to 3 hours of playback time. These earbuds feature Bluetooth v5.0 technology that delivers a stable connection that lets your rock on without connectivity issues",
        image:"https://rukminim2.flixcart.com/image/832/832/kfpq5jk0-0/headphone/2/k/w/rockerz-600-hd-sound-rockerz-610-boat-original-imafw3sc5r93kd9z.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kfpq5jk0-0/headphone/t/j/e/rockerz-600-hd-sound-rockerz-610-boat-original-imafw3scezrywhhk.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kfpq5jk0-0/headphone/c/l/a/rockerz-600-hd-sound-rockerz-610-boat-original-imafw3scywsu5ees.jpeg?q=70&crop=false",
        discount:"69%off",
        new_price:899,
        old_price:2990,
        rating:4
    } ,
    {
        id:80,
        name:"boAt Airdopes 161/163",
        full_name:"boAt Airdopes 161/163 (Pebble Black, Active Black, True Wireless))",
        brand_name:"boAt",
        category:"boat-headphones",
        description:"It's time to Do Your Groove, with Airdopes161TWS earbuds. The 13mm drivers in the earbuds are there to deliver an immersive listening time. It comes equipped with Bluetooth v5.1 wireless technology so that you can enjoy all of your sessions lag-free. The IWP tech enabled TWS earbuds power on as soon as the case lid gets opened. Moreover, the ASAP Charge tech helps the earbuds to gather up to 90 Mins of playtime in only 5 minutes of charging. Airdopes 161 provides a total playback time of up to 40HRS. ",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/o/d/r/-original-imagpgwsm6zgtsrj.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/9/x/u/-original-imagqtpfkwfzdydx.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/o/m/6/-original-imagqtpfj5yvdxwg.jpeg?q=70&crop=false",
        new_price:999,
        old_price:2490,
        discount:"59%off",
        rating:4
    },
    {
        id:81,
        name:"boAt Airdopes Supreme",
        full_name:"boAt Airdopes Supreme Bluetooth Headset(Classic Black, True Wireless)",
        brand_name:"boAt",
        category:"boat-headphones",
        description:"boAt Airdopes Supreme w/ 4 Mics AI ENx Tech, 50 HRS Playback,Multi Point Connectivity Bluetooth Headset  (Classic Black, True Wireless)//In- Ear Detection: Insert the buds to play/pause music, wear the earbuds to accept incoming calls & once removed the call gets transferred back to the phone.Spatial Audio Experience: Airdopes Supreme boasts real-time Spatial Audio with 24-Bit Audio Processing technology to bring you an immersive cinematic listening experience.50 Hours Playback with ASAP Charge: 10 Mins Charge= 150 Mins Playback.Beast Mode: Low Latency for Gaming",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/v/f/m/-original-imagz5z4cknamu9d.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/g/1/a/-original-imagz5z4uvyy3xzr.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/6/v/a/-original-imagz5z4v68u8sjj.jpeg?q=70&crop=false",
        new_price:1499,
        old_price:5990,
        discount:"74%off",
        rating:4.1
    },
    {
        id:82,
        name:"boAt Airdopes 131",
        full_name:"boAt Airdopes 131 Bluetooth Headset(Active Black,True Wireless)",
        brand_name:"boAt",
        category:"boat-headphones",
        description:"the boAt Airdopes 131 that comes with a carrying case. This carrying case also acts as a 650 mAh portable charger that extends the playback time of these earbuds by up to 15 hours, i.e. 4 times its normal charging capacity. The normal battery capacity of each of these earbuds is 40 mAh and this delivers up to 3 hours of playback time. These earbuds feature Bluetooth v5.0 technology that delivers a stable connection that lets your rock on without connectivity issues",
        image:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/1/8/l/-original-imagqhswqgpwb2yu.jpeg?q=70&crop=false",
        image_1:"https://rukminim2.flixcart.com/image/832/832/l23mhzk0/headphone/a/z/x/-original-imagdgumyuesnvhg.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/q/o/h/-original-imagjwgzgucg95g2.jpeg?q=70&crop=false",
        discount:"69%off",
        new_price:899,
        old_price:2990,
        rating:4
    } 
]
export default men_data;
// module.exports = { data: men_data };